{% set name = "doodleverse-utils" %}
{% set version = "0.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/doodleverse-utils-{{ version }}.tar.gz
  sha256: b72a59af05a56721cf741a976266dfef1794e76906a13e6bbf077e9a89046f3c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - doodleverse_utils
  commands:
    # bogus requirement on versioneer
    # - pip check
  requires:
    - pip

about:
  home: https://github.com/Doodleverse/doodleverse_utils
  summary: Imports into the Doodleverse
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
    - 2320sharon
